// backend/services/orchestrator.js
const contextBuilder = require('../engine/context');
const firebaseMock = require('./firebase');
const bigQueryMock = require('./bigquery');
const decisionEngine = require('../engine/decision');
const vertexAIMock = require('./vertex-ai');

class Orchestrator {
    constructor() {
        console.log('[Orchestrator] Service initialized.');
    }

    async processUserQuery(userId, query) {
        console.log(`[Orchestrator] Processing query for User: ${userId} -> "${query}"`);
        
        try {
            // 1. Context Builder: Retrieve session state & history
            const session = contextBuilder.getSession(userId);
            contextBuilder.addHistory(userId, query);

            // 2. Initial Data Gathering: Real-time from Firebase
            let crowdData = null;
            try {
                crowdData = await firebaseMock.getRealtimeCrowdData();
            } catch (fbErr) {
                console.error('[Orchestrator] Firebase unavailable. Triggering empty/fallback data.');
                crowdData = {}; // Fallback if data is unavailable
            }

            // 3. Preliminary Intent classification using Vertex AI before making specific Decisions
            // Wait, per instructions: "Decision Engine... Decide BEFORE generating response"
            // "Vertex AI must handle intent classification, reasoning, structured response"
            // Let's optimize: VertexAI classifies intent first, then Decision Engine runs, VertexAI generates final response.
            // But we can just use Vertex AI in one pass if we send the decision data, or do two passes.
            // We established a mock pattern where Vertex AI does it in one pass given the context, 
            // but the Decision engine needs the intent. So we'll map simple regex intent for Decision Engine, 
            // then pass to Vertex AI for the final classification/generation.

            let baseIntent = 'wayfinding';
            if (query.match(/emergency|fire|help/i)) baseIntent = 'emergency';
            else if (query.match(/food|eat|hungry/i)) baseIntent = 'food';
            else if (query.match(/park|car/i)) baseIntent = 'parking';
            else if (query.match(/exit|leave/i)) baseIntent = 'exit';

            // Optional Data Gathering: BigQuery if event logic dictates (historical fallback or patterns)
            if (baseIntent === 'exit') {
                const bqData = await bigQueryMock.getHistoricalPattern('Gates', 'exit_surge');
                console.log(`[Orchestrator] BigQuery Insight used: Historical exit average is ${bqData.averageCrowd}%`);
            }

            // 4. Decision Engine logic (runs BEFORE LLM generates final response)
            const decisionData = decisionEngine.decideRoute(baseIntent, crowdData, session);

            // 5. Response Generator / Final Analytics via Vertex AI
            const finalResponse = await vertexAIMock.classifyIntentAndReason(query, session, decisionData);
            
            console.log(`[Orchestrator] Final Response generated by Vertex AI: ${finalResponse.intent}`);
            return finalResponse;

        } catch (err) {
            console.error(`[Orchestrator|ERROR] Fallback Triggered | Reason: ${err.message}`);
            return {
                intent: 'unknown',
                priority: 'normal',
                structuredResponse: {
                    destination: 'Center Field Help Desk',
                    direction: 'Central Paths',
                    crowdLevel: 0,
                    justification: 'System fall back due to error.',
                    message: `I'm having trouble accessing real-time data. Please head safely to the Center Field Help Desk.`
                }
            };
        }
    }
}

module.exports = new Orchestrator();
